name: Push images to dockerhub and ghcr.io

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * 6'

jobs:
  build_and_upload_images_to_hub:
    name: Push images to dockerhub and github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "[ Prepare ] install missing packages"
        run: |
          sudo apt-get update
          sudo FRONTEND="noninteractive" apt-get -y install tzdata
          sudo apt-get install -y curl build-essential libssl-dev git golang gcc

      - name: "[ Prepare ] install globalsign/estclient"
        run: |
          pwd
          go get github.com/globalsign/est
          go get -u github.com/globalsign/est/cmd/estclient

      #- name: "Create images"
      #  run: |
      #    cat Docker/estclient/Dockerfile | docker build -t 3.2.0 -t grindsa/estclient -t ghcr.io/grindsa/estclient -f - .  --no-cache

      #- name: "upload images to hub.docker.com"
      #  run: |
      #    docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      #    docker push -a grindsa/estclient

      #- name: "upload images to ghcr.io"
      #  run: |
      #    docker login ghcr.io -u ${{ secrets.GHCR_USER }} -p ${{ secrets.GHCR_TOKEN }}
      #    docker push -a ghcr.io/grindsa/estclient
