name: create estclient image and push it dockerhub and ghcr.io

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * 6'

jobs:
  build_and_upload_images_to_hub:
    name: create estclient image and push it dockerhub and ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Create images"
        run: |
          cat Docker/estclient/Dockerfile | docker build -t 1.1.0 -t grindsa/estclient -t ghcr.io/grindsa/estclient -f - .  --no-cache

      - name: "upload images to hub.docker.com"
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push -a grindsa/estclient

      - name: "upload images to ghcr.io"
        run: |
          docker login ghcr.io -u ${{ secrets.GHCR_USER }} -p ${{ secrets.GHCR_TOKEN }}
          docker push -a ghcr.io/grindsa/estclient
